config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts
  end

  namespace :account do
    resources :groups
    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true

  has_many :posts, dependent: :destroy

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == owner
  end

  has_many :group_users
  has_many :members, through: :group_users, source: :user
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group, counter_cache: :posts_count

  belongs_to :author, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == author
  end

  scope :recent, -> { order("updated_at DESC")}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups.order("posts_count DESC")
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.recent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :warning, :info

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, onlt: [:new, :create, :edit, :update, :destroy]
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path
      flash[:notice] = "Group created"
    else
      render :new
    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])

    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path
    flash[:alert] = "Group has been removed"
  end

  private

  def group_params
    params.require(:group).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group

  def new

    @post = @group.posts.new
  end

  def create

    @post = @group.posts.build(post_params)
    @post.author = current_user

    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit

    @post = current_user.posts.find(params[:id])
  end

  def update

    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy

    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to group_path(@group)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_botton_options =
    { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_botton = content_tag(:botton, "x", close_botton_options)

    alerts = flash.map do |type, message|
      alert_content = close_botton + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

     alerts.join("\n").html_safe
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_post_content(post)
    simple_format(truncate(post.content, length: 30))
  end
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="">
        Welcome!!
      </a>
      <div class="nav navbar-nav">
        <li class="active"><%= link_to("Home", groups_path) %></li>
        <li class="active"><a href="https://instagram.com">Intagram</a> </li>
      </div>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("Sign Up", new_user_registration_path) %> </li>
          <li><%= link_to("Login", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              Hello, <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("My Groups", account_groups_path)%> </li>
              <li><%= link_to("My Posts", account_posts_path)%> </li>
              <li><%= link_to("Setting", edit_user_registration_path)%> </li>
              <li><%= link_to("Logout", destroy_user_session_path, method: :delete)%> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/groups/_form.html.erb
  <%= simple_form_for @group do |f| %>
    <div>
      <%= f.input :title %>
      <%= f.input :body %>
    </div>
    <%= f.submit "Save", class: "btn btn-default" %>
    <%= link_to("Back", groups_path(@group), class: "btn btn-default") %>
  <% end %>

app/views/groups/edit.html.erb
<h1 class="text-center">Edit Group</h1>
<div class="col-md-4 col-md-offset-4">
  <%= render "groups/form" %>
 </div>

app/views/groups/index.html.erb
<h1 class="text-center">cycling's always a good idea</h1>
<%= link_to("new", new_group_path, class: "btn btn-default" ) %>

<div>
  <table class="table table-hover">
    <thead>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(truncate(group.title, length: 15), group_path(group)) %></td>
          <td><%= group.body %></td>
          <td>
            <% if group.editable_by?(current_user) %>
              <%= link_to("edit", edit_group_path(group), class: "btn btn-default btn-sm") %>
              <%= link_to("remove", group_path(group), method: :delete,
              data: {confirm: "Sure?"},class: "btn btn-default btn-sm") %>
            <% end %>
          </td>
          <% end %>
        </tr>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<h1 class="text-center">New Group</h1>
<div class="col-md-4 col-md-offset-4">
  <%= render "groups/form" %>
 </div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div>
    <% if @group.editable_by?(current_user) %>
      <%= link_to("Edit Group", edit_group_path(@group), class: "btn btn-default pull-right")%>
    <% end %>
    <%= link_to("Add Post", new_group_post_path(@group), class: "btn btn-default pull-right")%>

    <% if current_user.present? %>
    <% if current_user.is_member_of?(@group) %>
      <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-default")%>

    <% else %>
      <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-default") %>
      <% end %>
    <% end %>
  </div>
  <h2>
    <%= @group.title %>
  </h2>
  <p><%= @group.body %> </p>
    <table class="table">
      <thead>
        <tr>
          <th>Content</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= simple_format(post.content) %></td>
            <td>
              <% if post.editable_by?(current_user) %>
              <%= link_to("edit", edit_group_post_path(post.group, post), class: "btn btn-default")%>
              <%= link_to("Remove", group_post_path(post.group, post), method: :delete, data: {confirm: "Sure?"}, class: "btn btn-default")%> </td>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render "common/navbar" %>
    <%= notice_message %>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/edit.html.erb
<h1 class="text-center">Edit Post</h1>
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group, @post] do |f| %>
    <div>
      <%= f.input :content %>
    </div>
    <%= f.submit "Save", class: "btn btn-default" %>
    <%= link_to("Back", groups_path(@group), class: "btn btn-default") %>
  <% end %>
 </div>

app/views/posts/new.html.erb
<h1 class="text-center">New Post</h1>
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group, @post] do |f| %>
    <div>
      <%= f.input :content %>
    </div>
    <%= f.submit "Save", class: "btn btn-default" %>
    <%= link_to("Back", groups_path(@group), class: "btn btn-default") %>
  <% end %>
 </div>